redis:
    image: redis
    ports:
        - "6379:6379"
mongo:
    image: aashreys/mongo-auth:latest
    volumes:
        - './mongo/data:/data/db'
    ports:
        - "27017:27017"
node:
    build: ./
    links:
        - redis
        - mongo
    ports:
        - "9500:3000"
        - "5858:5858"
    volumes:
        - .:/src
        - /src/node_modules
    environment:
        NODE_ENV: "development"
